# Effect and usage of activity_regularizer

In [22]:
import tensorflow as tf

layer = tf.keras.layers.Dense(5, kernel_initializer='ones',
                              activity_regularizer=tf.keras.regularizers.l2())

tensor = tf.ones(shape=(2, 5)).numpy() * 2.0
tensor[0, :] = [1,2,3,4,5]
tensor[1, :] = [6,7,8,9,10]

print("Input: \n", tensor)
out = layer(tensor)
print("Output: \n", out)

# The kernel regularization term is 0.25
# The activity regularization term (after dividing by the batch size) is 5
print("Layer losses:\n", tf.math.reduce_sum(layer.losses).numpy())  # 5.25 (= 5 + 0.25)

Input: 
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
Output: 
 tf.Tensor(
[[15. 15. 15. 15. 15.]
 [40. 40. 40. 40. 40.]], shape=(2, 5), dtype=float32)
Layer losses:
 45.625


### Regularizer is called with (nbatchsamples, latentdims) 

In [51]:
import keras.backend as K

class CustomReg(tf.keras.regularizers.Regularizer):
    def __call__(self, a):
        acc = K.sum(K.square(a[-1, :] * a[:-1, :]))
        return acc / (a.shape[-1]**2)

layer = tf.keras.layers.Dense(2, kernel_initializer='ones',
                              activity_regularizer=CustomReg())

tensor = tf.ones(shape=(2, 2)).numpy() * 2.0
tensor[0, :] = [1,2]
tensor[1, :] = [3,4]
# tensor[2, :] = [5,6]


print("Input: \n", tensor)
out = layer(tensor)
print("Output: \n", out)

print("Layer losses:\n", tf.math.reduce_sum(layer.losses).numpy())

Input: 
 [[1. 2.]
 [3. 4.]]
Output: 
 tf.Tensor(
[[3. 3.]
 [7. 7.]], shape=(2, 2), dtype=float32)
Layer losses:
 110.25
